#!/usr/bin/env node
// Removes cost/metrics from the published arcade output.
// Idempotent: safe to re-run. Run after every `promote`, before commit.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// 1. Strip metrics + changelog from every games/*/meta.json
const gamesDir = path.join(root, 'games');
let metaCount = 0;
for (const slug of fs.readdirSync(gamesDir)) {
  const f = path.join(gamesDir, slug, 'meta.json');
  if (!fs.existsSync(f)) continue;
  const m = JSON.parse(fs.readFileSync(f, 'utf8'));
  delete m.metrics;
  delete m.changelog;
  fs.writeFileSync(f, JSON.stringify(m, null, 2) + '\n');
  metaCount++;
}

// 2. Strip builtIn from data/games.js (format: header + `window.RG_GAMES = [...];`)
const gjPath = path.join(root, 'data', 'games.js');
const gj = fs.readFileSync(gjPath, 'utf8');
const start = gj.indexOf('[');
const end = gj.lastIndexOf(']');
const arr = JSON.parse(gj.slice(start, end + 1));
for (const e of arr) delete e.builtIn;
const out =
  '// AUTO-GENERATED by engine.arcade.promote — do not edit by hand.\n' +
  'window.RG_GAMES = ' + JSON.stringify(arr, null, 2) + ';\n';
fs.writeFileSync(gjPath, out);

console.log(`stripped cost from ${metaCount} meta.json + games.js`);
